- name: Authenticate clasp
  shell: bash
  run: |
    echo '${{ secrets.CLASPRC_JSON }}' > ~/.clasprc.json
    command -v jq >/dev/null || sudo apt-get update && sudo apt-get install -y jq
    jq . ~/.clasprc.json >/dev/null  # sanity check JSON
